### ISSUE TITLE
Morning session: peer-to-peer code reviews 1/24/2023

### ISSUE THREAD

**Issue by hansderly** [SFarida/to-do-list#5]
Good job meeting all the requirements for the task

There's only one minor change you can do: 
- You can store the value of your local storage in a variable and export it instead of typing it each time you want to use it
https://github.com/SFarida/to-do-list/blob/9d3652a5cd2c0ecd72248bd9f3cd5cc68934de2b/src/modules/tasks.js#L10

**Comment by SFarida** [comment]
Hello @hansderly thank you for the review I've fixed the issue.
